version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/redis_data
    networks:
      - mynetwork

  postgres:
    build: ./postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB : vectordb
    networks:
      - mynetwork


  service1:
    build: 
      context: ./Service1
      dockerfile: dockerfile    
    ports:
      - 5000:80
    depends_on:
      - postgres
      - service2
    networks:
      - mynetwork
  
  service2:
    build: 
      context: ./Service2
      dockerfile: dockerfile    
    ports:
      - 8000:80
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - mynetwork

volumes:
  redis_data:
  redis2_data:

networks:
  mynetwork:
    driver: bridge