FROM python:3.12-slim

WORKDIR /app 

COPY . /app

RUN pip install --no-cache-dir fastapi uvicorn redis requests openai langchain langchain_community python-dotenv sqlalchemy postgres psycopg2-binary pgvector tiktoken

# install postgres client
RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*


# Copy and wait for postgres.sh and make it executable
COPY ./wait-for-postgres.sh /wait-for-postgres.sh
RUN chmod +x /wait-for-postgres.sh

EXPOSE 80

CMD ["/wait-for-postgres.sh","postgres","uvicorn","app:app","--host","0.0.0.0","--port","80"]

