version: '3.9'

services:
  api:
    build: 
    ports:
      - "7755: 7755"
  
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml : /etc/prometheus/prometheus.yml
    ports:
      - "9090: 9090"
  
  grafana:
    image: grafana/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    volumes:
      - grafana-data: /varr/lib/grafana
    depends_on:
      - prometheus
volumes:
  - grafana-data:


     
     

