"""Added_Mobile_column

Revision ID: 0e1e7e274a25
Revises: af768b726566
Create Date: 2024-07-13 10:46:54.255970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e1e7e274a25'
down_revision: Union[str, None] = 'af768b726566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('mobile', sa.String(length=13), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'mobile')
    # ### end Alembic commands ###
